# Generated by Django 3.2.5 on 2021-10-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/images.jpg', upload_to='uploads/profile_pictures'),
        ),
    ]
